"""gauge column

Revision ID: 058a686a8a05
Revises: f1e33dff20d1
Create Date: 2024-12-26 23:16:08.641595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '058a686a8a05'
down_revision = 'f1e33dff20d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_gauges', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('product_gauges')

    # ### end Alembic commands ###
