"""Adjusting product category 

Revision ID: 78757f2d8094
Revises: 8b2e7e31caa7
Create Date: 2024-12-12 14:44:31.461499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78757f2d8094'
down_revision = '8b2e7e31caa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'categories', ['product_category_id'], ['category_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
