"""orders status

Revision ID: f62b7f583e3f
Revises: cd006ff092ce
Create Date: 2024-12-17 18:54:57.848942

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f62b7f583e3f'
down_revision = 'cd006ff092ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('total_amount', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('total_price')
        batch_op.drop_column('contact_number')
        batch_op.drop_column('shipping_address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_address', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('contact_number', mysql.VARCHAR(length=15), nullable=False))
        batch_op.add_column(sa.Column('total_price', mysql.FLOAT(), nullable=False))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('status')
        batch_op.drop_column('total_amount')
        batch_op.drop_column('customer_name')

    # ### end Alembic commands ###
